# kindly generated by appropriated Rails generator
require "mailjet"

Mailjet.configure do |config|
  config.api_key = ENV["MJ_API_KEY"]
  config.secret_key = ENV["MJ_SECRET_KEY"]
  config.default_from = ENV["MJ_SENDER_ADRESS"]
  config.api_version = "v3.1"
end
